### ISSUE TITLE
Porque não possui em criar uma fatura uma opção de descontos ou taxas extras?

### ISSUE THREAD

**Issue by brunolalencar** [gerencianet/gn-api-sdk-php#1]
Seria ideal ter uma opção de enviar descontos e/ou taxas extras pois facilita muito em integrações a sistema que possui cupons de descontos e vale presentes.

**Comment by dannielhugo** [comment]
Em breve disponibilizaremos um recurso que permite enviar descontos por forma de pagamento. Acredito que isso solucione o seu problema.

Estou marcando esta issue com o label "feature" e assim que ela for disponibilizada você será notificado.

**Comment by dannielhugo** [comment]
@brunolalencar 
Disponibilizamos na Api Gerencianet a possibilidade de enviar descontos específicos por forma de pagamento.
Segue o link da documentação: 
https://github.com/gerencianet/gn-api-sdk-php/blob/master/docs/CHARGE_PAYMENT.md#3-discount-by-payment-method
