### ISSUE TITLE
Problema ao instalar pacote via composer

### ISSUE THREAD

**Issue by jgustavo99** [gerencianet/gn-api-sdk-php#10]
Olá! Fui instalar o pacote via composer e retornou um erro de dependências:

  Problem 1
    - gerencianet/gerencianet-sdk-php 1.0.0 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.1 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.10 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.11 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.12 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.2 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.3 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.4 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.5 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.6 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.7 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - gerencianet/gerencianet-sdk-php 1.0.9 requires codeclimate/php-test-reporter ^0.1.2 -> satisfiable by codeclimate/php-test-reporter[v0.1.2].
    - Conclusion: don't install codeclimate/php-test-reporter v0.1.2
    - Installation request for gerencianet/gerencianet-sdk-php ^1.0 -> satisfiable by gerencianet/gerencianet-sdk-php[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.9].

O que está acontecendo?

**Comment by fseduardo** [comment]
+1

**Comment by asaferamos** [comment]
Conseguiu resolver? Estou com o mesmo problema.

**Comment by eduardo76** [comment]
Eu resolvi fazendo eu mesmo novos pacotes, porém atualizados.

Segue os links:
Github: https://github.com/eduardo76/gerencianet
Packagist: https://packagist.org/packages/eduardo/gerencianet-sdk-php-atualizado

É o mesmo código, porém com as bibliotecas atualizadas.
Obs: Não são repositórios oficiais, mas estão funcionando.

**Comment by silasrm** [comment]
O problema deve ser resolvido simplesmente colocando o codeclimate/php-test-reporter como pacote requerido para desenvolvimento, pois é um pacote para coleta de dados de teste e envio para o code climate. Não deveria está como requerido globalmente.

**Comment by FilipeMata** [comment]
Boa tarde, pessoal

O problema foi resolvido com a sugestão do @silasrm. Agradecemos a sugestão, @silasrm.
A atualização está disponível na release 1.0.14.

Qualquer outra dúvida, entrem em contato com o nosso suporte através da criação de ticket. Estes tickets são enviados diretamente para o nosso setor de suporte técnico, o que facilita bastante a resolução de um problema.

**Comment by silasrm** [comment]
De nada :D
