### ISSUE TITLE
Remover subscription com status NEW

### ISSUE THREAD

**Issue by vesteves** [gerencianet/gn-api-sdk-php#11]
Pessoal,
Cheguei a testar junto ao Tiago, por telefone, e verificamos que ao tentar dar um hit em /v1/subscription/:id/cancel e este id estiver com status NEW, ele não é cancelado e é retornado um erro alertando que este subscription não existe.
![print](https://user-images.githubusercontent.com/14235724/27500111-4d384804-583d-11e7-9335-b2450c8a2d82.png)
![print2](https://user-images.githubusercontent.com/14235724/27500112-4d3cffc0-583d-11e7-8d75-88fd454da261.png)
Mesmo como verificamos que isso não afeta em nada para a Gerencianet, é um incômodo ter que fazer mais uma validação no sistema para verificar status NEW como se fosse Cancelado.

**Comment by chuckbnorris** [comment]
@vesteves essa questão foi aberta internamente e peço por gentileza que aguarde o retorno da equipe responsável.

Contudo, gostaria de pedir encarecidamente que nas próximas vezes, que primeiro faça a abertura do ticket em nosso [suporte](https://dev.gerencianet.com.br/docs/fale-conosco), pois é um dos canais oficiais de comunicação com nossa empresa e agiliza o repasse interno, além é claro de ficar registrado em nossa ferramenta de ticket.

Qualquer dúvida, estou à disposição.

**Comment by guilhermecotaGn** [comment]
Olá, @vesteves!
Tal modificação já é possível ser realizada em nossa API.
