### ISSUE TITLE
Confirmar pagamento manual e enviar comprovante de pagamento via API

### ISSUE THREAD

**Issue by marciodiasdeveloper** [gerencianet/gn-api-sdk-php#12]
É possível implementar nova rotina? opções extras como confirmar pagamento manual e enviar comprovante de pagamento via API.

**Comment by chuckbnorris** [comment]
@marciodiasdev 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Estamos lançando para nossos clientes, de forma gradativa, uma nova plataforma de gestão que permitirá a baixa manual de um pagamento. Isso será feito, a princípio, dentro do seu painel, e não pela API. Caso sua conta Gerencianet já tenha sido migrada, você já está com acesso a este recurso; caso ainda não tenha sido migrada, peço por gentileza que aguarde pois as migrações continuam sendo realizadas gradualmente.

Quanto a enviar comprovante de pagamento via API, isto ainda não é possível. Deixaremos registrado como uma sugestão para nossa equipe, tudo bem?

Caso precise abrir ticket ou falar com nosso suporte, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Qualquer coisa, estou à disposição.
