### ISSUE TITLE
como identificar um retorno de erro?

### ISSUE THREAD

**Issue by williamsgomes** [gerencianet/gn-api-sdk-php#13]
Olá, estou implementando o Gerencianet em nosso sistema para a geração dos boletos. Estamos ultilizando o API com PHP.

Porém minha dúvida é como posso saber se o retorno ocorrido foi o 200? Ou seja se tudo ocorreu bem?

Pois precisava no PHP dizer se caso o retorno não tenha sido 200 para gerar um alerta e/ou refazer o processo.

Podem me ajudar com isso?

**Comment by chuckbnorris** [comment]
@williamsgomes 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Claro, podemos ajudá-lo sim. Separei um exemplo de retorno de um consumo bem sucedido de um boleto, ou seja, após enviar uma requisição POST para a rota /charge/:id/pay e os dados inputados estiverem corretos (de acordo com as validações da API), você obterá um retorno como [este da imagem](https://www.screencast.com/t/PEXopONg).

Repare especificamente a linha 2, é justamente nela que você pode realizar suas devidas tratativas. Agora, fiz de forma proposital um erro ao inputar determinadas informações ao consumir o /charge/:id/pay, e observe [nesta imagem](https://www.screencast.com/t/J99tlzdYDShG) o retorno que obtive. Repare na linha linha 2 e confira que o retorno desta vez foi diferente de "200".

Em nossa documentação, temos uma página que poderá ajudá-lo, o nome dela é "[Interpretando Erros na API](https://dev.gerencianet.com.br/docs/interpretando-erros-api)".

Caso precise abrir ticket ou falar com nosso suporte, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Espero ter esclarecido sua dúvida. O que necessitar, conte conosco.
