### ISSUE TITLE
config.json sem os EndPoints SettleCharge

### ISSUE THREAD

**Issue by santiagomarcos** [gerencianet/gn-api-sdk-php#15]
Pessoal, boa noite. 
A versão 2.2.0 está sem os EndPoints de Settle no final do config.json.

![image](https://user-images.githubusercontent.com/9480552/46709362-c2d83c80-cc19-11e8-828d-d7e00f3822ac.png)

Poderiam verificar por gentileza?

**Comment by limabibi** [comment]
Olá boa tarde,

Estou passando pela mesma situação, ao tentar fazer a integração do sistema com a GerenciaNET, para marcar como pago de forma manual usando "settleCharge" retorna "nonexistent endpoint".

Reforçando, poderiam verificar por gentileza?

Desde já grata.

**Comment by rafwell** [comment]
+1

**Comment by chuckbnorris** [comment]
@santiagomarcos e @rafwell 

O referido endpoint já foi inserido.
Agradecemos pela informação ;)
