### ISSUE TITLE
Problema com timeout

### ISSUE THREAD

**Issue by patrickjvieira** [gerencianet/gn-api-sdk-php#26]
$this->option não existe, o que existe é $this->config
https://github.com/gerencianet/gn-api-sdk-php/blob/bb23a9e96a9303a44dee4a9dbdb500d7e3f0eb5d/src/Gerencianet/Auth.php#L37

Se a ideia é coletar a variável timeout da array config então precisa adicionar esse código
https://github.com/gerencianet/gn-api-sdk-php/blob/bb23a9e96a9303a44dee4a9dbdb500d7e3f0eb5d/src/Gerencianet/Config.php#L31
```
 if (isset($options['timeout'])) {
       $conf['timeout'] = $options['timeout'];
 }
```

**Comment by guilhermecotaGn** [comment]
Olá, @patrickjvieira. Obrigado por sua contribuição!
Realizamos a atualização na versão [3.1.0](https://github.com/gerencianet/gn-api-sdk-php/tree/3.1.0)
