### ISSUE TITLE
Guzzle v7 é imcompatível

### ISSUE THREAD

**Issue by davi5e** [gerencianet/gn-api-sdk-php#29]
Instalar via `composer require gerencianet/gerencianet-sdk-php` gera um erro se o pacote `guzzlehttp/guzzle` já estiver presente em `composer.lock` com versão superior à [v7](https://github.com/guzzle/guzzle).

A limitação de usar apenas [v6](https://github.com/guzzle/guzzle/tree/6.5) pode gerar problemas no longo prazo ou quando entrar em EOL.

A solução é o downgrade da versão do Guzzle até as dependências serem ajustadas.

[Guzzle Version Guidance](https://github.com/guzzle/guzzle#version-guidance).

**Comment by fajusto** [comment]
Tive este problema e fiz o downgrade, mas não gostei nada. Espero que corrijam isso logo...

**Comment by Overx** [comment]
Aguardando também

**Comment by alexmontoanelli** [comment]
Mais um na fila..

**Comment by TaffarelXavier** [comment]
Mesmo problema.

**Comment by guilhermecotaGn** [comment]
Agradecemos pelo feedback pessoal! 
Realizamos o upgrade da SDK para versão [4.0.0](https://github.com/gerencianet/gn-api-sdk-php/tree/4.0.0), onde atualizamos o Guzzle para versão >= 7.0 e o PHP >= 7.2
