### ISSUE TITLE
Problema de Invalid resource type: boolean

### ISSUE THREAD

**Issue by loja5combr** [gerencianet/gn-api-sdk-php#3]
Ola, uso este sdk em meus módulos mas muitos clientes estão com problema que ocorre ocasionalmente, depois que gera a cobrança e vai realizar o pagamento gera o erro a seguir:
Invalid resource type: boolean

Buscando vi que este erro ocorre no Guzzle que não permite envio de inteiros e boleanos no corpo, e o sdk usa Guzzle, já viram este problema ou se já foi corrigido?

https://github.com/guzzle/guzzle/issues/628

**Comment by ceciliadeveza** [comment]
Olá @loja5combr,

Conseguimos reproduzir o erro alterando a codificação dos arquivos que utilizam a SDK. Por favor, altere a codificação de todos os arquivos para UTF-8 e tente novamente.

**Comment by eliemarjunior** [comment]
Cecilia, uma coisa que me ajudou com este erro foi colocar utf8_encode na hora de setar o nome do cliente:
$customer = [
    'name' => utf8_encode($nome),
    'cpf' => $cpf,
    'phone_number' => $telefone
];

Acredito que irá ajudar outras pessoas.
