### ISSUE TITLE
QR estático

### ISSUE THREAD

**Issue by capedra** [gerencianet/gn-api-sdk-php#38]
Como gerar cobranças que gerem qr codes estáticos e que possibilitem o uso de webhooks/callbacks? E que tragam todas as informações do pagador. Grato, Caio!

**Comment by guilhermecotaGn** [comment]
Olá, @capedra. Como vai?
No caso para cobranças a partir de uma QR Code estático, não é necessário a criação da cobrança via API.

Ou seja, você mesmo que irá programar seu sistema para gerar o código EMV (Pix Copia e Cola) do QR Code estático. Para isso, você deve seguir os [padrões do BR Code definidos pelo Banco Central](https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoI-PadroesParaIniciacaodoPix.pdf).

Um detalhe muito interessante é que, você montando este QR Code estático, se ele possuir um txid (identificado único), e uma chave Pix registrada na Gerencianet e que possui um webhook registrado, a Gerenciant irá enviar a notificação deste Pix quando confirmado.
