### ISSUE TITLE
QR reutilizável

### ISSUE THREAD

**Issue by capedra** [gerencianet/gn-api-sdk-php#39]
Como posso/poderia configurar o atributo Point of Initiation Method (PIM) através da API da Gerencianet? Gostaria de poder configurar o valor 11 para QR reutilizável e 12 para não reutilizável. Grato, Caio!

**Comment by guilhermecotaGn** [comment]
Olá, @capedra. Como vai?

De acordo com as [definições do Banco Central](https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoI-PadroesParaIniciacaodoPix.pdf), um [QR Code dinâmico não pode ser pago](https://gnetbr.com/HJlJb69gnu) mais de uma vez. Contudo, não há como configurar o atributo Point of Initiation Method que é gerado através da API.

Este atributo pode ser configurado em QR Code estáticos gerados por você.
