### ISSUE TITLE
Erro ao gerar pagamento

### ISSUE THREAD

**Issue by atiladelcanton** [gerencianet/gn-api-sdk-php#4]
property_does_not_existsArray ( [property] => id [message] => A propriedade [id] informada não existe. )

**Comment by mpmnicolau** [comment]
**O fluxo para gerar cobranças:**
1. Gera o /charge. Uma das respostas do consumo será o charge_id.
2. Se for uma cobrança por cartão de crédito, é necessário gerar o _payment_token_ via javascript, utilizando a biblioteca pronta da Gerencianet, presente dentro da API na sua conta (em Meios de Pagamento > Cartão). Se for boleto, o payment_token não é necessário.
3. Consumir _/charge/:id/pay_. O id presente nesse endpoint é o charge_id gerado no passo 1 desse fluxo. É nesse passo que é definido o tipo de cobrança (boleto ou cartão) em que a charge gerada no passo 1 será paga.

**Importante:**
É aconselhável verificar o Playground (plataforma de testes) dentro da aplicação criada na API em sua conta Gerencianet. A utilização do Playground dá uma boa idéia do funcionamento da API, e facilita a continuidade de suas atividades de integração.

_Em caso de dúvidas, basta entrar em [contato ](https://gerencianet.com.br/central-de-ajuda) com a Gerencianet._

Toda a documentação pode ser verificada em [Documentação](https://docs.gerencianet.com.br).

**Comment by mpmnicolau** [comment]
**Complementando:**

Se estiver utilizando o SDK da Gerencianet, esse erro provavelmente ocorreu na utilização da função payCharge(). Um exemplo de consumo dessa função pode ser verificado [aqui](https://github.com/gerencianet/gn-api-sdk-php/blob/master/examples/charge/billet.php).
Veja que o ID mostrado do erro é o id da charge criada no passo 1 conforme explicado no fluxo anterior. Consulte a [documentação ](https://docs.gerencianet.com.br) para verificar como criar charge.
