### ISSUE TITLE
Favorecido sem pix

### ISSUE THREAD

**Issue by superlogicabrunocosta** [gerencianet/gn-api-sdk-php#41]
https://github.com/gerencianet/gn-api-sdk-php/blob/09c5d4adc095ac0b30b4dff929e21e70a7a22188/examples/pix/pix/pixSend.php#L19

Há casos que o favorecido não tem PIX, não tem como ser de outra maneira neste caso?!

**Comment by SadyCoimbraEfi** [comment]
Para esses casos você pode utilizar o envio através de dados bancários, conforme demonstrado no exemplo 2 em nossa documentação, acessível pelo link:
https://dev.gerencianet.com.br/docs/api-pix-endpoints#section-requisitar-envio-de-pix
