### ISSUE TITLE
Ao criar um pix

### ISSUE THREAD

**Issue by brunoribeiro-lab** [gerencianet/gn-api-sdk-php#42]
Notice: Undefined index: error_description in /home/meuprojeto/public_html/vendor/gerencianet/gerencianet-sdk-php/src/Gerencianet/Exception/GerencianetException.php on line 21

Notice: Undefined index: error in /home/meuprojeto/public_html/vendor/gerencianet/gerencianet-sdk-php/src/Gerencianet/Exception/GerencianetException.php on line 27

Notice: Undefined index: error_description in /home/meuprojeto/public_html/vendor/gerencianet/gerencianet-sdk-php/src/Gerencianet/Exception/GerencianetException.php on line 28

Notice: Undefined index: code in /home/meuprojeto/public_html/vendor/gerencianet/gerencianet-sdk-php/src/Gerencianet/Exception/GerencianetException.php on line 30

Esse erro sumiu quando atualizei a SDK, vi que teve uma atualização em um arquivo há 26 dias, mas pelo que notei só foi fixado esse alerta, a exceção não retorna nenhum erro.

Isso é quando cria uma chave ou gera um pix, não é sempre que aparece essa mensagem, e quando não aparece o PIX ou a chave são gerados certinho ou seja o código está funcionando, é só algumas exceções.

**Comment by guilhermecotaGn** [comment]
Olá, @brunoribeiro-lab. Tudo bem contigo?

Compreendi. Realizamos análises do código nos trechos indicados, e diversos testes utilizando a versão atual da SDK (4.1.1), mas não conseguimos simular esta falha apresentada para identificar o problema.

Acreditamos que esta falha possa ter ocorrido devido a uma instabilidade nos serviços da AWS (Amazon Web Services) na terça-feira, 07/12/2021, que acabaram afetando nossa API, que não estava respondendo corretamente.

Caso ainda tenha dificuldades, sugiro acessar nossa [comunidade no servidor do Discord](https://gerencianet.github.io/gn-comunidade-discord/). Você pode me procurar lá, que ficará mais fácil de me passar os detalhes.

**Comment by guilhermecotaGn** [comment]
Caso o problema seja na SSK reportaremos neste issue.
