### ISSUE TITLE
Curl 28 -  Criação de Charge One Step

### ISSUE THREAD

**Issue by MarceloxAlves** [gerencianet/gn-api-sdk-php#45]
Ao criar um boleto, não é possível obter resposta da requisição, mas o boleto é criado no painel. O boleto foi criado no ambiente de homologação. Seguindo os passos da documentação:  [Criação de Boleto em One Step (Um passo)](https://dev.gerencianet.com.br/v1/docs/gerar-boleto-bancario#section-1-cria-o-de-boleto-em-one-step-um-passo-)

`string(196) "cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://sandbox.gerencianet.com.br/v1/charge/one-step"`

**Comment by guilhermecotaGn** [comment]
Olá, @MarceloxAlves! Tudo bem?
Atualmente somente no ambiente de homologação está tendo um tempo maior de resposta nas requisições, ocasionando na falha ""cURL error 28: Operation timed".

Para solucionar, sugiro aumentar o timeout para 60 no parâmetro que está definido no arquivo [/examples/config.json](https://github.com/gerencianet/gn-api-sdk-php/blob/master/examples/config.json) junto com as credenciais.
