### ISSUE TITLE
Pix Endpoints - Cobranças com vencimento (COBV)

### ISSUE THREAD

**Issue by dadeke** [gerencianet/gn-api-sdk-php#46]
Olá pessoal. 🙋🏻‍♂️

Estou utilizando esse sdk para criar a cobrança Pix com data de vencimento.

Foi então que notei que está faltando esses _endpoints_:

```
PUT /v2/cobv/:txid
PATCH /v2/cobv/:txid
GET /v2/cobv
GET /v2/cobv/:txid
```

Já adicionei eles no [src/Gerencianet/config.json](https://github.com/gerencianet/gn-api-sdk-php/blob/master/src/Gerencianet/config.json)

Então posso enviar um _pull request_?

**Comment by guilhermecotaGn** [comment]
Olá, @dadeke. Tudo bem com você?

Desde já, agradecemos seu contato e colaboração! Comunico que nossa SDK foi atualizada para a v5.0.0 que agora abrange todos os [endpoits do cobV](https://github.com/gerencianet/gn-api-sdk-php/tree/master/examples/pix/cobv) (Pix com vencimento), dentre outras novidades e melhorias.

Caso ainda tenha dificuldades, acesse também nossa [comunidade do Discord](https://gerencianet.github.io/gn-comunidade-discord/).
