### ISSUE TITLE
Forçando versão 7.4 do guzzlehttp/guzzle

### ISSUE THREAD

**Issue by thiagoflessak** [gerencianet/gn-api-sdk-php#49]
Olá,

Desde a versão 5.1.2 a dependência guzzlehttp/guzzle está declarada de forma específica para a versão 7.4:

`"guzzlehttp/guzzle": "7.4"`

Onde o correto deveria ser:

`"guzzlehttp/guzzle": "^7.4"`

**Comment by guilhermecotaGn** [comment]
Olá, @thiagoflessak! Como vai?

A correção foi realizada na versão 5.1.4.

Aproveito para comunicar que esta SDK de PHP da Gerencianet continua em funcionamento, mas foi descontinuada e não receberá mais atualizações. Recomendamos que migre para a nova SDK da Efí para continuar desfrutando de nossos serviços e novidades. Saiba mais em: [github.com/efipay/sdk-php-apis-efi](https://github.com/efipay/sdk-php-apis-efi). Inclusive, você pode usar o [validador de migração](https://github.com/gerencianet/gn-api-sdk-php#validador-de-migra%C3%A7%C3%A3o) para facilitar o processo.

Agradecemos a contribuição!

**Comment by guilhermecotaGn** [comment]
Olá, @thiagoflessak! Como vai?

A correção foi realizada na versão 5.1.4.

Aproveito para comunicar que esta SDK de PHP da Gerencianet continua em funcionamento, mas foi descontinuada e não receberá mais atualizações. Recomendamos que migre para a nova SDK da Efí para continuar desfrutando de nossos serviços e novidades. Saiba mais em: [github.com/efipay/sdk-php-apis-efi](https://github.com/efipay/sdk-php-apis-efi). Inclusive, você pode usar o [validador de migração](https://github.com/gerencianet/gn-api-sdk-php#validador-de-migra%C3%A7%C3%A3o) para facilitar o processo.

Agradecemos pela contribuição!
