### ISSUE TITLE
Undefined variable $message

### ISSUE THREAD

**Issue by dadeke** [gerencianet/gn-api-sdk-php#50]
Sempre quando acontece alguma _Exception_ está retornando essa mensagem:

#### PHP version: 8.1.17

```log
ErrorException {#3444
  #message: "Undefined variable $message"
  #code: 0
  #line: 48
  #severity: E_WARNING
}
```

Está indicando que a variável `$message` aqui na linha 48 está fora do escopo:

https://github.com/gerencianet/gn-api-sdk-php/blob/5b68d26b9586b2fe5b1ad202dfc03368f37d1789/src/Gerencianet/Exception/GerencianetException.php#L24-L49

Inicializando `$message = null;` dentro do escopo do método deverá solucionar esta questão.
Então posso enviar um pull request sobre isso? 👨‍💻

**Comment by guilhermecotaGn** [comment]
A SDK de PHP da Gerencianet continua em funcionamento, porém não receberá mais atualizações. Recomendamos que migre para a nova [SDK da Efí](https://github.com/efipay/sdk-php-apis-efi) para continuar desfrutando de nossos serviços, novidades e que inclusive possui esta correção.

Para facilitar esse processo desenvolvemos o **Validador de Migração**, [veja mais detalhes](https://github.com/efipay/sdk-php-apis-efi#validador-de-migra%C3%A7%C3%A3o).
