### ISSUE TITLE
Guzzlehttp muito desatualizado

### ISSUE THREAD

**Issue by jonathaniqueda** [gerencianet/gn-api-sdk-php#6]
Pessoal,

Quando rodei o composer require do SDK de vocês deu conflito com o Guzzle que eu estou rodando no projeto (6.0.2). Percebi que você usam o 5.3.0, existe alguma previsão de update?

Att.

**Comment by jotafurtado** [comment]
Mesmo problema aqui comigo. Vou verificar se consigo faze rum downgrade no meu projeto para utilizar com o pacote de vocês. Um atualização seria bem vinda.

**Comment by jotafurtado** [comment]
Sem chance, não consegui fazer downgrade no meu projeto. Muitas dependências. Vou ter que criar um projeto paralelo.

**Comment by jonathaniqueda** [comment]
Acabei me ferrando por aqui... Vou tentar criar um project externo ou mexer no composer deles e alterar a SDK.

**Comment by mpmnicolau** [comment]
@jonathaniqueda @jotafurtado 
Pessoal, com o composer da forma que está abaixo é possível que as duas versões do Guzzle funcionem ao mesmo tempo no projeto.

{
  "require": {
    "gerencianet/gerencianet-sdk-php": "1.0",
    "guzzlehttp/guzzle": "6.0"
  }
}

Por favor, dando certo ou errado, poderiam me dar um feedback?

**Comment by jonathaniqueda** [comment]
@mpmnicolau Por aqui estava exatamente assim e foi isso que gerou o erro. Conseguir converter meu Guzzle para 5.3.0, porém recomendo muito que vocês atualizem isso. A galera raramente usa essa versão old.

**Comment by eduardo76** [comment]
Pessoal, se ainda interessar a vocês, eu tive o mesmo problema da biblioteca está desatualizada.
Então eu resolvi atualizar eu mesmo.

Segue os links:
Github: https://github.com/eduardo76/gerencianet
Packagist: https://packagist.org/packages/eduardo/gerencianet-sdk-php-atualizado

É o mesmo código, porém com as bibliotecas atualizadas.
Obs: Não são repositórios oficiais, mas estão funcionando.

**Comment by jotafurtado** [comment]
@eduardo76 faz um PR quem sabe eles aceitam. Acabei mudando de plataforma, não uso mais o GerenciaNet. Mas essa atualização é bem vinda de qualquer forma.

**Comment by guicouto** [comment]
Estou com o mesmo problema aqui por causa do Guzzle muito desatualizado.

**Comment by jgustavo99** [comment]
Um sistema de pagamento igual Gerencianet, n deveria ter problemas assim num pacote de integração oficial. Por favor, corrigem o problema, já está a uns meses assim...

**Comment by vesteves** [comment]
O estranho é que o downgrade da versão do guzzle foi acontecendo conforme o sistema foi avançando. a versão 1.0.1 usava a 6~ enquanto as mais atuais estão usando a 5.3~
Deve ter algum motivo técnico para isso. Seria interessante se algum membro oficial da equipe fizesse o report.

```
Problem 1
    - gerencianet/gerencianet-sdk-php 1.0.9 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.7 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.6 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.5 requires guzzlehttp/guzzle 6.0.2 -> satisfiable by guzzlehttp/guzzle[6.0.2] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.4 requires guzzlehttp/guzzle 6.0.2 -> satisfiable by guzzlehttp/guzzle[6.0.2] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.3 requires guzzlehttp/guzzle 6.0.2 -> satisfiable by guzzlehttp/guzzle[6.0.2] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.2 requires guzzlehttp/guzzle 6.0.2 -> satisfiable by guzzlehttp/guzzle[6.0.2] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.12 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.11 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.10 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.1 requires guzzlehttp/guzzle 6.0.2 -> satisfiable by guzzlehttp/guzzle[6.0.2] but these conflict with your requirements or minimum-stability.
    - gerencianet/gerencianet-sdk-php 1.0.0 requires guzzlehttp/guzzle 6.0.2 -> satisfiable by guzzlehttp/guzzle[6.0.2] but these conflict with your requirements or minimum-stability.
    - Installation request for gerencianet/gerencianet-sdk-php ^1.0 -> satisfiable by gerencianet/gerencianet-sdk-php[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.9]
```

**Comment by marciodiasdeveloper** [comment]
#fail

composer require gerencianet/gerencianet-sdk-php
Using version ^1.0 for gerencianet/gerencianet-sdk-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle (locked at 6.2.3) -> satisfiable by guzzlehttp/guzzle[6.2.3].
    - gerencianet/gerencianet-sdk-php 1.0.10 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - gerencianet/gerencianet-sdk-php 1.0.11 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - gerencianet/gerencianet-sdk-php 1.0.12 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - gerencianet/gerencianet-sdk-php 1.0.6 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - gerencianet/gerencianet-sdk-php 1.0.7 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - gerencianet/gerencianet-sdk-php 1.0.9 requires guzzlehttp/guzzle 5.3.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.0

**Comment by lucianotonet** [comment]
O pessoal do suporte do GerenciaNet normalmente são bem prestativos através dos tickets de suporte deles.
Abri um agora informando sobre esta questão. Vamos ver se assim eles providenciam uma solução.
![image](https://cloud.githubusercontent.com/assets/2693019/26184324/9c6442c0-3b5a-11e7-8fa4-45dceb7dac74.png)

**Comment by vesteves** [comment]
De qquer maneira, gostaria de avisar que consegui integrar mas foi bem trabalhoso ter que achar as versões exatas de cada dependência.
Caso queiram ver o resultado, é só acessar o meu sistema.
https://www.tallybox.com.br/

**Comment by lucianotonet** [comment]
Segue resposta do suporte:
![image](https://cloud.githubusercontent.com/assets/2693019/26201350/f1baa9be-3ba8-11e7-9349-1915f2259fec.png)

Link arquivo informado: https://gerencianet.com.br/material/api/php/api.zip
Documentação: https://dev.gerencianet.com.br/docs/instalacao-sdk-php?#section-4-instala-o-biblioteca-php-da-gerencianet-sem-o-composer

Não vou poder testar agora.
Alguém se prontifica?

**Comment by marciodiasdeveloper** [comment]
+1, irei testar.

**Comment by vesteves** [comment]
Inviável pq tem frameworks (Laravel por exemplo) que usam as mesmas dependências que o Gerencianet e, no Laravel, eles estão na última versão e, ao tentar usar o composer, terá q dar downgrade.
Usando esta base de arquivos irá sobrescrever e dar conflito de versão com as já existentes.
O correto a ser feito é atualizar ou informar o motivo pelo qual usam versões anteriores dos pacotes.

**Comment by marciodiasdeveloper** [comment]
estou precisando muito integrar a lib ao meu laravel5.4, vou tentar usar guzzle direto sem utilizar a lib oficial, bem que rolava um update neste sdk

**Comment by chuckbnorris** [comment]
@vesteves, @marciodiasdev e todos outros que estão lendo esta mensagem:

Me chamo Tiago, faço parte da equipe técnica da Gerencianet, atuo especificamente na área de Integrações da API Gerencianet.

Conforme podem notar, o @tonetlds utilizou nossa ferramenta de suporte (ticket), eu mesmo o respondi e expliquei com detalhes: ofereci uma medida paliativa e mencionei que estaria encaminhando internamente essa demanda aos responsáveis técnicos. Entendo plenamente o que está sendo abordado neste _issue_, por isso já encaminhei internamente para que verifiquem à respeito. Caso não tenham visto, peço por gentileza que acessem a [mensagem](https://github.com/gerencianet/gn-api-sdk-php/issues/6#issuecomment-302385114) do @tonetlds e leiam com atenção o que foi que respondi via ticket.

Sempre que precisarem, podem entrar em contato conosco. O ideal é sempre utilizar as [ferramentas oficiais](https://dev.gerencianet.com.br/docs/fale-conosco) de suporte da empresa, sendo o ticket uma delas (não precisa nem ser cadastrado na Gerencianet para enviar ticket).

Ademais, peço por gentileza a compreensão de vocês. Assim que houver retorno por parte de nossa equipe técnica, irei responder através do referido ticket e este próprio _issue_, só peço mais um pouco de paciência.

Qualquer dúvida ou informação adicional, estamos à disposição.

**Comment by eduardo76** [comment]
Pessoal, se ainda interessar a vocês, eu tive o mesmo problema da biblioteca está desatualizada.
Então eu resolvi atualizar eu mesmo.

Segue os links:
Github: https://github.com/eduardo76/gerencianet
Packagist: https://packagist.org/packages/eduardo/gerencianet-sdk-php-atualizado

É o mesmo código, porém com as bibliotecas atualizadas.
Obs: Não são repositórios oficiais, mas estão funcionando.
Obs2: Eu uso Laravel5.4

**Comment by vesteves** [comment]
> Pessoal, se ainda interessar a vocês, eu tive o mesmo problema da biblioteca está desatualizada.
>Então eu resolvi atualizar eu mesmo.
>
>Segue os links:
>Github: https://github.com/eduardo76/gerencianet
>Packagist: https://packagist.org/packages/eduardo/gerencianet-sdk-php-atualizado
>
>É o mesmo código, porém com as bibliotecas atualizadas.
>Obs: Não são repositórios oficiais, mas estão funcionando.
>Obs2: Eu uso Laravel5.4

@eduardo76  obrigado pela iniciativa mas me sinto mais seguro utilizando a solução oficial pois trafego dados importantes por esta API.
Seria de uma enorme ajuda se vc entrasse em contato com o suporte da Gerencianet e disponibilizasse como fez para atualizar todos os pacotes. Talvez assim eles agilizem o processo.

**Comment by marciodiasdeveloper** [comment]
@eduardo76 seu package também não passou ....

> Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 6.2.3].
    - Can only install one of: guzzlehttp/guzzle[6.2.3, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 6.2.3].
    - eduardo/gerencianet-sdk-php-atualizado 1.0.11 requires guzzlehttp/guzzle 6.2.2 -> satisfiable by guzzlehttp/guzzle[6.2.2].
    - Installation request for eduardo/gerencianet-sdk-php-atualizado ^1.0 -> satisfiable by eduardo/gerencianet-sdk-php-atualizado[1.0.11].
    - Installation request for guzzlehttp/guzzle (locked at 6.2.3, required as ^6.2) -> satisfiable by guzzlehttp/guzzle[6.2.3].

**Comment by whallysson** [comment]
O que fiz para consertar isso, foi depois de instalar pelo composer não funcionava(mesmo erro da galera).
Criei uma nova pasta, fiz um download do zip (https://github.com/gerencianet/gn-api-sdk-php/archive/master.zip) , abri o o composer.json do download e alterei o "guzzlehttp/guzzle": "5.3.0" para "guzzlehttp/guzzle": "5.3.1".
Dei um "composer install" nessa nova pasta, e depois substitui a pasta "vendor/guzzlehttp" que estava com erro por essa do download. :)

**Comment by vesteves** [comment]
@tiagoxpl Nenhuma previsão ainda?
Estou precisando deste pacote na versão acima da ^6.2 para usar passport do Laravel em meu projeto...

**Comment by chuckbnorris** [comment]
@vesteves Sim, nosso desenvolvimento já está trabalhando e pelo retorno que obtive, nos próximos dias estará oficialmente solucionado. Fique tranquilo, vou avisá-los aqui assim que subirem em produção.

**Comment by FilipeMata** [comment]
Boa tarde, pessoal.
Acabamos de atualizar o nosso repositório com os reparos solicitados para SDK-PHP. 
As novas atualizações incluem:
- Compatibilidade com PHP 5.5, 5.6, 7.0 e 7.1
- Upgrade para a versão mais recente do Guzzle 6.

Na documentação do [Guzzle](https://github.com/guzzle/guzzle) é possível notar que as versões mais recentes são compatíveis apenas com versões superiores do PHP 5.5.
Para atender à estes requisitos tivemos que restringir a versão do PHP para a nova atualização da nossa SDK.

A SDK Gerencianet-PHP compatível com a versão 5.4 do PHP ainda está disponível em nossa branch [1.x](https://github.com/gerencianet/gn-api-sdk-php/tree/1.x). Porém é importante frisar que a versão do Guzzle para esta versão da SDK ainda é a 5.3.

**Comment by chuckbnorris** [comment]
@vesteves, @whallysson, @marciodiasdev, @eduardo76, @tonetlds, @jgustavo99, @guicouto, @jotafurtado, @jonathaniqueda
