### ISSUE TITLE
Incluir sem composer

### ISSUE THREAD

**Issue by arthurbonora** [gerencianet/gn-api-sdk-php#7]
Afinal qual arquivo devo incluir caso não deseje utilizar o composer e colocar a sdk direto no diretório?

**Comment by mpmnicolau** [comment]
Arthur,
entre em contato com a Consultoria Técnica da Gerencianet.
Eles conseguirão te ajudar.
https://gerencianet.com.br/central-de-ajuda/

**Comment by arthurbonora** [comment]
@mpmnicolau ok, muito obrigado

**Comment by ghost** [comment]
@arthurbonora Resposta enviada, confira seu email por gentileza.
