### ISSUE TITLE
Falta opção de timeout para as request

### ISSUE THREAD

**Issue by daniel-abrahao** [gerencianet/gn-api-sdk-php#9]
[Por padrão](http://docs.guzzlephp.org/en/5.3/clients.html#timeout) o Guzzle espera indefinidamente a request terminar. Se há algum problema na rede, ou nos servidores, da forma que está não é possível para a aplicação tomar alguma decisão quando a resposta demora muito para vir. Em geral o servidor web ou o FPM vai interromper a execução do código no meio e retornar um HTTP 500.
Seria legal se houvesse um timeout padrão, ou melhor ainda, se fosse possível configurar o timeout.

Imgino que pela estrutura do sdk teria que ser algo como:
```php
// na inicialização
$Api = new Gerencianet([
	'client_id' => $apiKeys['client_id'],
	'client_secret' => $apiKeys['client_secret'],
	'sandbox' => true,
	'timeout' => 30 // segundos
]);

// ou
$Api->setTimeout(30);
$Api->createCharge([], $body);
```

**Comment by FilipeMata** [comment]
Bom dia, @daniel-abrahao 
A nossa SDK foi tualizada para atender a sua demanda. Na versão 1.0.14 é possível definir um timeout ao instanciar o objeto Gerencianet.

Caso tenha outras demandas, sugiro fortemente que entre em contato com o nosso suporte através da criação de tickets. A sua requisição será analisada por uma equipe de suporte técnico, e caso necessário, sua dúvida será encaminhada para o setor adequado o mais rápido possível.
